export const testReportTerms = [
    "RBC Count",
    "Rheumatoid Factor (RF) Test",
    "Respiratory Pathogens Panel",
    "Renal Function Test",
    "Random Blood Sugar",
    
    "Liver Function Test (LFT)",
    "Electrolyte Panel",
    "Thyroid-Stimulating Hormone (TSH)",
    "Complete Blood Count (CBC)",
    "Lipid Profile",
    "Prothrombin Time (PT)",
    "Partial Thromboplastin Time (PTT)",
    "Alanine Aminotransferase (ALT)",
    "Aspartate Aminotransferase (AST)",
    "Bilirubin, Total and Direct",
    "Uric Acid",
    "Blood Urea Nitrogen (BUN)",
    "Creatinine Clearance",
    "Ferritin Test",
    "Calcium Test",
    "Vitamin D Test",
    "Folic Acid Test",
    "Iron, Total Iron-Binding Capacity (TIBC)",
    "Glucose Tolerance Test (GTT)",
    "C-Reactive Protein (CRP)",
    "Erythrocyte Sedimentation Rate (ESR)",
    "D-Dimer Test",
    "Bone Density Test",
    "Magnesium Test",
    "Phosphorus Test",
    "Gamma-Glutamyl Transferase (GGT)",
    "Troponin Test",
    "Lactate Dehydrogenase (LDH)",
    "Amylase Test",
    "Lipase Test",
    "Microalbumin Test",
    "Urinalysis",
    "Cholesterol Test",
    "Triglycerides",
    "Blood Pressure",
    "Body Mass Index (BMI)",
    "White Blood Cell Count (WBC)",
    "Platelet Count",
    "Electrocardiogram (ECG)",
    "Echocardiogram",
    "Chest X-Ray",
    "CT Scan",
    "MRI Scan",
    "Ultrasound",
    "Positron Emission Tomography (PET) Scan",
    "Pulmonary Function Test (PFT)",
    "Blood Culture",
    "Hepatitis B Surface Antigen (HBsAg)",
    "Hepatitis C Antibody Test",
    "HIV Antibody Test",
    "Blood Gas Analysis",
    "Spirometry Test",
    "Allergy Test",
    "Skin Prick Test",
    "Pap Smear",
    "Mammogram",
    "Prostate-Specific Antigen (PSA) Test",
    "Stool Test",
    "Fecal Occult Blood Test",
    "H. Pylori Test",
    "Antinuclear Antibody (ANA) Test",
    "Immunoglobulins (IgA, IgG, IgM)",
    "Cancer Antigen 125 (CA-125)",
    "Carcinoembryonic Antigen (CEA)",
    "Beta-Human Chorionic Gonadotropin (Beta-hCG)",
    "Tumor Markers",
    "Hormone Panel",
    "Sexually Transmitted Disease (STD) Panel",
    "Insulin Test",
    "Cortisol Test",
    "Parathyroid Hormone (PTH) Test",
    "Testosterone Test",
    "Estradiol Test",
    "Progesterone Test",
    "Kidney Function Panel",
    "Bone Mineral Density Test",
    "Arterial Blood Gas (ABG)",
    "Sodium Test",
    "Potassium Test",
    "Chloride Test",
    "Bicarbonate Test",
    "Osmolality Test",
    "Lymphocyte Count",
    "Monocyte Count",
    "Eosinophil Count",
    "Basophil Count",
    "Zinc Test",
    "Copper Test",
    "Manganese Test",
    "Cobalt Test",
    "Lead Test",
    "Mercury Test",
    "Arsenic Test",
    "Hemoglobin",
  "White Blood Cell (WBC) Count",
  "White Blood Cell (WBC)",
  "Red Blood Cell (RBC) Count",
  "Red Blood Cell (RBC)",
  "Platelet Count",
  "Blood Glucose Level",
  "Cholesterol",
  "Triglycerides",
  "HDL (High-Density Lipoprotein)",
  "LDL (Low-Density Lipoprotein)",
  "Blood Urea Nitrogen (BUN)",
  "Creatinine",
  "Electrolytes",
  "Calcium",
  "Potassium",
  "Sodium",
  "C-Reactive Protein (CRP)",
  "Thyroid-Stimulating Hormone (TSH)",
  "Vitamin D",
  "Vitamin B12",
  "Alkaline Phosphatase",
  "Alanine Transaminase (ALT)",
  "Aspartate Transaminase (AST)",
  "Albumin",
  "Globulin",
  "Bilirubin",
  "Prothrombin Time (PT)",
  "Partial Thromboplastin Time (PTT)",
  "Erythrocyte Sedimentation Rate (ESR)",
  "Iron",
  "Ferritin",
  "Lipid Profile",
  "Complete Blood Count (CBC)",
  "Liver Function Test (LFT)",
  "Kidney Function Test (KFT)",
    // Add additional terms if needed
  ];
  